In [46]:
import pandas as pd

In [47]:
dataset = [['<=30','high','false','fair','no'],
          ['<=30','high','false','excellent','no'],
          ['31...40','high','false','fair','yes'],
          ['>40','medium','false','fair','yes'],
          ['>40','low','true','fair','yes'],
          ['>40','low','true','excellent','no'],
          ['31...40','low','true','excellent','yes'],
          ['<=30','medium','false','fair','no'],
          ['<=30','low','true','fair','yes'],
          ['>40','medium','true','fair','yes'],
          ['<=30','medium','true','excellent','yes'],
          ['31...40','medium','false','excellent','yes'],
          ['31...40','high','true','fair','yes'],
          ['>40','medium','false','excellent','no']]

In [48]:
df = pd.DataFrame(dataset, columns = ['age','income','student', 'credit_rating', 'buys_computer'])

In [49]:
df

        age  income student credit_rating buys_computer
0      <=30    high   false          fair            no
1      <=30    high   false     excellent            no
2   31...40    high   false          fair           yes
3       >40  medium   false          fair           yes
4       >40     low    true          fair           yes
5       >40     low    true     excellent            no
6   31...40     low    true     excellent           yes
7      <=30  medium   false          fair            no
8      <=30     low    true          fair           yes
9       >40  medium    true          fair           yes
10     <=30  medium    true     excellent           yes
11  31...40  medium   false     excellent           yes
12  31...40    high    true          fair           yes
13      >40  medium   false     excellent            no

In [50]:
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,31...40,<=30,>40,excellent,fair,false,high,low,medium,no,true,yes
0,False,True,False,False,True,True,True,False,False,True,False,False
1,False,True,False,True,False,True,True,False,False,True,False,False
2,True,False,False,False,True,True,True,False,False,False,False,True
3,False,False,True,False,True,True,False,False,True,False,False,True
4,False,False,True,False,True,False,False,True,False,False,True,True
5,False,False,True,True,False,False,False,True,False,True,True,False
6,True,False,False,True,False,False,False,True,False,False,True,True
7,False,True,False,False,True,True,False,False,True,True,False,False
8,False,True,False,False,True,False,False,True,False,False,True,True
9,False,False,True,False,True,False,False,False,True,False,True,True
10,False,True,False,True,False,False,False,False,True,False,True,True
11,True,False,False,True,False,True,False,False,True,False,False,True
12,True,False,False,False,True,False,True,False,False,False,True,True
13,False,False,True,True,False,True,False,False,True,True,False,False

In [51]:
x=apriori(df, min_support=0.1, use_colnames=True)

In [52]:
temp = x
temp

      support                  itemsets
0    0.285714                 (31...40)
1    0.357143                    (<=30)
2    0.357143                     (>40)
3    0.428571               (excellent)
4    0.571429                    (fair)
..        ...                       ...
99   0.142857   (no, fair, <=30, false)
100  0.142857   (no, false, <=30, high)
101  0.142857  (yes, fair, >40, medium)
102  0.142857    (fair, true, >40, yes)
103  0.142857    (fair, true, low, yes)

[104 rows x 2 columns]

In [53]:
temp['length']=temp['itemsets'].apply(lambda x:len(x))
temp

      support                  itemsets  length
0    0.285714                 (31...40)       1
1    0.357143                    (<=30)       1
2    0.357143                     (>40)       1
3    0.428571               (excellent)       1
4    0.571429                    (fair)       1
..        ...                       ...     ...
99   0.142857   (no, fair, <=30, false)       4
100  0.142857   (no, false, <=30, high)       4
101  0.142857  (yes, fair, >40, medium)       4
102  0.142857    (fair, true, >40, yes)       4
103  0.142857    (fair, true, low, yes)       4

[104 rows x 3 columns]

In [36]:
temp = temp[temp['length']>=2]

In [38]:
temp

      support                    itemsets  length
17   0.285714              (31...40, yes)       2
25   0.142857                 (<=30, yes)       2
33   0.214286                  (>40, yes)       2
39   0.214286            (excellent, yes)       2
46   0.428571                 (fair, yes)       2
50   0.214286                (false, yes)       2
52   0.142857                 (high, yes)       2
54   0.214286                  (low, yes)       2
57   0.285714               (yes, medium)       2
58   0.428571                 (true, yes)       2
59   0.142857   (31...40, excellent, yes)       3
61   0.142857        (fair, 31...40, yes)       3
62   0.142857       (false, 31...40, yes)       3
63   0.142857        (31...40, high, yes)       3
64   0.142857        (true, 31...40, yes)       3
70   0.142857           (true, <=30, yes)       3
74   0.214286            (fair, >40, yes)       3
77   0.142857          (yes, >40, medium)       3
78   0.142857            (true, >40, yes)       3
82   0.142857    (excellent, yes, medium)       3
83   0.142857      (true, excellent, yes)       3
87   0.142857          (fair, false, yes)       3
88   0.142857           (fair, high, yes)       3
90   0.142857            (fair, low, yes)       3
91   0.142857         (fair, yes, medium)       3
92   0.285714           (fair, true, yes)       3
95   0.142857        (false, yes, medium)       3
96   0.214286            (true, low, yes)       3
97   0.142857         (true, yes, medium)       3
98   0.142857  (fair, 31...40, high, yes)       4
101  0.142857    (yes, fair, >40, medium)       4
102  0.142857      (fair, true, >40, yes)       4
103  0.142857      (fair, true, low, yes)       4
23   0.214286                  (<=30, no)       2
31   0.142857                   (no, >40)       2
37   0.214286             (excellent, no)       2
44   0.142857                  (fair, no)       2
49   0.285714                 (false, no)       2
51   0.142857                  (no, high)       2
55   0.142857                (no, medium)       2
66   0.142857            (fair, <=30, no)       3
68   0.214286           (false, <=30, no)       3
69   0.142857            (no, <=30, high)       3
71   0.142857        (excellent, no, >40)       3
80   0.142857      (excellent, false, no)       3
86   0.142857           (false, fair, no)       3
93   0.142857           (false, no, high)       3
94   0.142857         (false, no, medium)       3
99   0.142857     (no, fair, <=30, false)       4
100  0.142857     (no, false, <=30, high)       4

In [56]:
from mlxtend.frequent_patterns import association_rules
result = association_rules(temp,metric='confidence',min_threshold=0.6)
result

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(31...40),(yes),0.285714,0.642857,0.285714,1.000000,1.555556,0.102041,inf
1,(<=30),(fair),0.357143,0.571429,0.214286,0.600000,1.050000,0.010204,1.071429
2,(<=30),(false),0.357143,0.500000,0.214286,0.600000,1.200000,0.035714,1.250000
3,(<=30),(no),0.357143,0.357143,0.214286,0.600000,1.680000,0.086735,1.607143
4,(no),(<=30),0.357143,0.357143,0.214286,0.600000,1.680000,0.086735,1.607143
...,...,...,...,...,...,...,...,...,...
140,"(fair, true, low)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
141,"(fair, low, yes)",(true),0.142857,0.500000,0.142857,1.000000,2.000000,0.071429,inf
142,"(true, low, yes)",(fair),0.214286,0.571429,0.142857,0.666667,1.166667,0.020408,1.285714
143,"(fair, low)","(true, yes)",0.142857,0.428571,0.142857,1.000000,2.333333,0.081633,inf
144,"(low, yes)","(fair, true)",0.214286,0.285714,0.142857,0.666667,2.333333,0.081633,2.142857

In [61]:
x1 = result.loc[result['consequents']== {'yes'}]
x2 = result.loc[result['consequents']== {'no'}]
x3 = pd.concat([x1,x2])

In [73]:
temp1 = x3.loc[x3['antecedents'].str.contains('<=30',regex=False)]
temp2 = x3.loc[x3['antecedents'].str.contains('medium',regex=False)]
temp3 = x3.loc[x3['antecedents'].str.contains('true',regex=False)]
temp4 = x3.loc[x3['antecedents'].str.contains('fair',regex=False)]
pd.concat([temp1,temp2,temp3,temp4]).drop_duplicates().reset_index(drop=True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(<=30, true)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
1,(<=30),(no),0.357143,0.357143,0.214286,0.600000,1.680000,0.086735,1.607143
2,"(fair, <=30)",(no),0.214286,0.357143,0.142857,0.666667,1.866667,0.066327,1.928571
3,"(false, <=30)",(no),0.214286,0.357143,0.214286,1.000000,2.800000,0.137755,inf
4,"(<=30, high)",(no),0.142857,0.357143,0.142857,1.000000,2.800000,0.091837,inf
5,"(fair, <=30, false)",(no),0.142857,0.357143,0.142857,1.000000,2.800000,0.091837,inf
6,"(false, <=30, high)",(no),0.142857,0.357143,0.142857,1.000000,2.800000,0.091837,inf
7,(medium),(yes),0.428571,0.642857,0.285714,0.666667,1.037037,0.010204,1.071429
8,"(>40, medium)",(yes),0.214286,0.642857,0.142857,0.666667,1.037037,0.005102,1.071429
9,"(excellent, medium)",(yes),0.214286,0.642857,0.142857,0.666667,1.037037,0.005102,1.071429
10,"(fair, medium)",(yes),0.214286,0.642857,0.142857,0.666667,1.037037,0.005102,1.071429
11,"(true, medium)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
12,"(fair, >40, medium)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
13,(true),(yes),0.500000,0.642857,0.428571,0.857143,1.333333,0.107143,2.500000
14,"(true, 31...40)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
15,"(true, >40)",(yes),0.214286,0.642857,0.142857,0.666667,1.037037,0.005102,1.071429
16,"(true, excellent)",(yes),0.214286,0.642857,0.142857,0.666667,1.037037,0.005102,1.071429
17,"(fair, true)",(yes),0.285714,0.642857,0.285714,1.000000,1.555556,0.102041,inf
18,"(true, low)",(yes),0.285714,0.642857,0.214286,0.750000,1.166667,0.030612,1.428571
19,"(fair, true, >40)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
20,"(fair, true, low)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
21,(fair),(yes),0.571429,0.642857,0.428571,0.750000,1.166667,0.061224,1.428571
22,"(fair, 31...40)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
23,"(fair, >40)",(yes),0.214286,0.642857,0.214286,1.000000,1.555556,0.076531,inf
24,"(fair, high)",(yes),0.214286,0.642857,0.142857,0.666667,1.037037,0.005102,1.071429
25,"(fair, low)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf
26,"(fair, 31...40, high)",(yes),0.142857,0.642857,0.142857,1.000000,1.555556,0.051020,inf

### Only index with 0,1,2,7,10,11,13,17,21 satisfied all test input.

### The highest confident rules predicts class = Yes.
### Thus predict Yes.